namespace FrogEdu.Exam.Domain.Enums;

public enum QuestionSource
{
    Manual = 1, // Created manually by teachers
    AIGenerated = 2, // Generated by AI
    Imported = 3, // Imported from external sources
    CurriculumBank = 4, // From official curriculum question bank
}
