// <auto-generated />
using System;
using FrogEdu.Class.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrogEdu.Class.Infrastructure.Migrations
{
    [DbContext(typeof(ClassDbContext))]
    [Migration("20260217225501_AddExamSessions")]
    partial class AddExamSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_Assignments_ClassId");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Assignments_DueDate");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_Assignments_ExamId");

                    b.ToTable("Assignments", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_ClassEnrollments_ClassId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ClassEnrollments_Status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_ClassEnrollments_StudentId");

                    b.HasIndex("ClassId", "StudentId")
                        .HasDatabaseName("IX_ClassEnrollments_ClassId_StudentId");

                    b.ToTable("ClassEnrollments", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("InviteCode");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Grade")
                        .HasDatabaseName("IX_ClassRooms_Grade");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ClassRooms_InviteCode");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ClassRooms_IsActive");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_ClassRooms_TeacherId");

                    b.ToTable("ClassRooms", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowPartialScoring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRetryable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RetryTimes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("ShouldShuffleAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ShouldShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_ExamSessions_ClassId");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("IX_ExamSessions_EndTime");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_ExamSessions_ExamId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ExamSessions_IsActive");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_ExamSessions_StartTime");

                    b.HasIndex("ClassId", "ExamId")
                        .HasDatabaseName("IX_ExamSessions_ClassId_ExamId");

                    b.ToTable("ExamSessions", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.StudentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPartiallyCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("SelectedAnswerIds")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("IX_StudentAnswers_AttemptId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentAnswers_AttemptId_QuestionId");

                    b.ToTable("StudentAnswers", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.StudentExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId")
                        .HasDatabaseName("IX_StudentExamAttempts_ExamSessionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_StudentExamAttempts_Status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_StudentExamAttempts_StudentId");

                    b.HasIndex("ExamSessionId", "StudentId")
                        .HasDatabaseName("IX_StudentExamAttempts_SessionId_StudentId");

                    b.ToTable("StudentExamAttempts", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("FrogEdu.Class.Domain.Entities.ClassRoom", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassEnrollment", b =>
                {
                    b.HasOne("FrogEdu.Class.Domain.Entities.ClassRoom", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.StudentAnswer", b =>
                {
                    b.HasOne("FrogEdu.Class.Domain.Entities.StudentExamAttempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.StudentExamAttempt", b =>
                {
                    b.HasOne("FrogEdu.Class.Domain.Entities.ExamSession", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassRoom", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.StudentExamAttempt", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
