// <auto-generated />
using System;
using FrogEdu.Class.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrogEdu.Class.Infrastructure.Migrations
{
    [DbContext(typeof(ClassDbContext))]
    partial class ClassDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_Assignments_ClassId");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Assignments_DueDate");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_Assignments_ExamId");

                    b.ToTable("Assignments", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_ClassEnrollments_ClassId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ClassEnrollments_Status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_ClassEnrollments_StudentId");

                    b.HasIndex("ClassId", "StudentId")
                        .HasDatabaseName("IX_ClassEnrollments_ClassId_StudentId");

                    b.ToTable("ClassEnrollments", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("InviteCode");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Grade")
                        .HasDatabaseName("IX_ClassRooms_Grade");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ClassRooms_InviteCode");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ClassRooms_IsActive");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_ClassRooms_TeacherId");

                    b.ToTable("ClassRooms", "public");
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("FrogEdu.Class.Domain.Entities.ClassRoom", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassEnrollment", b =>
                {
                    b.HasOne("FrogEdu.Class.Domain.Entities.ClassRoom", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Class.Domain.Entities.ClassRoom", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
