// <auto-generated />
using System;
using FrogEdu.Exam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrogEdu.Exam.Infrastructure.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20260202160459_UpdateSubjectIndexAndSeedData")]
    partial class UpdateSubjectIndexAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsCorrect")
                        .HasDatabaseName("IX_Answers_IsCorrect");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("IX_Answers_QuestionId");

                    b.ToTable("Answers", "public");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("PassScore")
                        .HasColumnType("integer");

                    b.Property<bool>("ShouldShuffleAnswerOptions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ShouldShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Exams_AccessCode")
                        .HasFilter("[AccessCode] IS NOT NULL");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Exams_CreatedBy");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Exams_IsActive");

                    b.HasIndex("IsDraft")
                        .HasDatabaseName("IX_Exams_IsDraft");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("IX_Exams_TopicId");

                    b.ToTable("Exams", "public");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("ExamId", "QuestionId");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_ExamQuestions_ExamId");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("IX_ExamQuestions_QuestionId");

                    b.ToTable("ExamQuestions", "public");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Matrix", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamId")
                        .IsUnique()
                        .HasDatabaseName("IX_Matrices_ExamId");

                    b.ToTable("Matrices", "public");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.MatrixTopic", b =>
                {
                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("CognitiveLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MatrixId", "TopicId", "CognitiveLevel");

                    b.HasIndex("MatrixId")
                        .HasDatabaseName("IX_MatrixTopics_MatrixId");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("IX_MatrixTopics_TopicId");

                    b.ToTable("MatrixTopics", "public");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CognitiveLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("Point")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CognitiveLevel")
                        .HasDatabaseName("IX_Questions_CognitiveLevel");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Questions_CreatedBy");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_Questions_IsPublic");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("IX_Questions_TopicId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Questions_Type");

                    b.ToTable("Questions", "public");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Grade")
                        .HasDatabaseName("IX_Subjects_Grade");

                    b.HasIndex("SubjectCode", "Grade")
                        .IsUnique()
                        .HasDatabaseName("IX_Subjects_SubjectCode_Grade");

                    b.ToTable("Subjects", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Study of numbers, quantities, and shapes",
                            Grade = 1,
                            Name = "Mathematics",
                            SubjectCode = "math"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Study of past events and Earth's features",
                            Grade = 1,
                            Name = "History & Geography",
                            SubjectCode = "history_geography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "English language and literature",
                            Grade = 1,
                            Name = "English",
                            SubjectCode = "english"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "Study of written works and literary analysis",
                            Grade = 1,
                            Name = "Literature",
                            SubjectCode = "literature"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "Computer science and digital technology",
                            Grade = 1,
                            Name = "Information Technology",
                            SubjectCode = "it"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Description = "Applied science and engineering",
                            Grade = 1,
                            Name = "Technology",
                            SubjectCode = "technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Description = "Visual arts and creative expression",
                            Grade = 1,
                            Name = "Art",
                            SubjectCode = "art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Description = "Study of natural world and physical phenomena",
                            Grade = 1,
                            Name = "Science",
                            SubjectCode = "science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Description = "Musical theory and performance",
                            Grade = 1,
                            Name = "Music",
                            SubjectCode = "music"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Hands-on learning and practical experiences",
                            Grade = 1,
                            Name = "Experiential Activities",
                            SubjectCode = "experiential_activities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Study of numbers, quantities, and shapes",
                            Grade = 2,
                            Name = "Mathematics",
                            SubjectCode = "math"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Study of past events and Earth's features",
                            Grade = 2,
                            Name = "History & Geography",
                            SubjectCode = "history_geography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Description = "English language and literature",
                            Grade = 2,
                            Name = "English",
                            SubjectCode = "english"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Description = "Study of written works and literary analysis",
                            Grade = 2,
                            Name = "Literature",
                            SubjectCode = "literature"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Description = "Computer science and digital technology",
                            Grade = 2,
                            Name = "Information Technology",
                            SubjectCode = "it"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Description = "Applied science and engineering",
                            Grade = 2,
                            Name = "Technology",
                            SubjectCode = "technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Description = "Visual arts and creative expression",
                            Grade = 2,
                            Name = "Art",
                            SubjectCode = "art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Description = "Study of natural world and physical phenomena",
                            Grade = 2,
                            Name = "Science",
                            SubjectCode = "science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Description = "Musical theory and performance",
                            Grade = 2,
                            Name = "Music",
                            SubjectCode = "music"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Description = "Hands-on learning and practical experiences",
                            Grade = 2,
                            Name = "Experiential Activities",
                            SubjectCode = "experiential_activities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Description = "Study of numbers, quantities, and shapes",
                            Grade = 3,
                            Name = "Mathematics",
                            SubjectCode = "math"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Description = "Study of past events and Earth's features",
                            Grade = 3,
                            Name = "History & Geography",
                            SubjectCode = "history_geography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Description = "English language and literature",
                            Grade = 3,
                            Name = "English",
                            SubjectCode = "english"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Description = "Study of written works and literary analysis",
                            Grade = 3,
                            Name = "Literature",
                            SubjectCode = "literature"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Description = "Computer science and digital technology",
                            Grade = 3,
                            Name = "Information Technology",
                            SubjectCode = "it"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Description = "Applied science and engineering",
                            Grade = 3,
                            Name = "Technology",
                            SubjectCode = "technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Description = "Visual arts and creative expression",
                            Grade = 3,
                            Name = "Art",
                            SubjectCode = "art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Description = "Study of natural world and physical phenomena",
                            Grade = 3,
                            Name = "Science",
                            SubjectCode = "science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Description = "Musical theory and performance",
                            Grade = 3,
                            Name = "Music",
                            SubjectCode = "music"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Description = "Hands-on learning and practical experiences",
                            Grade = 3,
                            Name = "Experiential Activities",
                            SubjectCode = "experiential_activities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Description = "Study of numbers, quantities, and shapes",
                            Grade = 4,
                            Name = "Mathematics",
                            SubjectCode = "math"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Description = "Study of past events and Earth's features",
                            Grade = 4,
                            Name = "History & Geography",
                            SubjectCode = "history_geography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Description = "English language and literature",
                            Grade = 4,
                            Name = "English",
                            SubjectCode = "english"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            Description = "Study of written works and literary analysis",
                            Grade = 4,
                            Name = "Literature",
                            SubjectCode = "literature"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            Description = "Computer science and digital technology",
                            Grade = 4,
                            Name = "Information Technology",
                            SubjectCode = "it"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            Description = "Applied science and engineering",
                            Grade = 4,
                            Name = "Technology",
                            SubjectCode = "technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            Description = "Visual arts and creative expression",
                            Grade = 4,
                            Name = "Art",
                            SubjectCode = "art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            Description = "Study of natural world and physical phenomena",
                            Grade = 4,
                            Name = "Science",
                            SubjectCode = "science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            Description = "Musical theory and performance",
                            Grade = 4,
                            Name = "Music",
                            SubjectCode = "music"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            Description = "Hands-on learning and practical experiences",
                            Grade = 4,
                            Name = "Experiential Activities",
                            SubjectCode = "experiential_activities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            Description = "Study of numbers, quantities, and shapes",
                            Grade = 5,
                            Name = "Mathematics",
                            SubjectCode = "math"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            Description = "Study of past events and Earth's features",
                            Grade = 5,
                            Name = "History & Geography",
                            SubjectCode = "history_geography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            Description = "English language and literature",
                            Grade = 5,
                            Name = "English",
                            SubjectCode = "english"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            Description = "Study of written works and literary analysis",
                            Grade = 5,
                            Name = "Literature",
                            SubjectCode = "literature"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            Description = "Computer science and digital technology",
                            Grade = 5,
                            Name = "Information Technology",
                            SubjectCode = "it"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            Description = "Applied science and engineering",
                            Grade = 5,
                            Name = "Technology",
                            SubjectCode = "technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            Description = "Visual arts and creative expression",
                            Grade = 5,
                            Name = "Art",
                            SubjectCode = "art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            Description = "Study of natural world and physical phenomena",
                            Grade = 5,
                            Name = "Science",
                            SubjectCode = "science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            Description = "Musical theory and performance",
                            Grade = 5,
                            Name = "Music",
                            SubjectCode = "music"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            Description = "Hands-on learning and practical experiences",
                            Grade = 5,
                            Name = "Experiential Activities",
                            SubjectCode = "experiential_activities"
                        });
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCurriculum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsCurriculum")
                        .HasDatabaseName("IX_Topics_IsCurriculum");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Topics_SubjectId");

                    b.ToTable("Topics", "public");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Answer", b =>
                {
                    b.HasOne("FrogEdu.Exam.Domain.Entities.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("FrogEdu.Exam.Domain.Entities.Exam", null)
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrogEdu.Exam.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Matrix", b =>
                {
                    b.HasOne("FrogEdu.Exam.Domain.Entities.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.MatrixTopic", b =>
                {
                    b.HasOne("FrogEdu.Exam.Domain.Entities.Matrix", null)
                        .WithMany("MatrixTopics")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrogEdu.Exam.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Question", b =>
                {
                    b.HasOne("FrogEdu.Exam.Domain.Entities.Topic", null)
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Topic", b =>
                {
                    b.HasOne("FrogEdu.Exam.Domain.Entities.Subject", null)
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Exam", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Matrix", b =>
                {
                    b.Navigation("MatrixTopics");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("FrogEdu.Exam.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
