import type { CognitiveLevel, QuestionType } from './exam-service/enums'

// Re-export request types for convenience
export type {
	GenerateQuestionsRequest,
	GenerateSingleQuestionRequest,
} from '@/types/dtos/ai'

// ========================================
// Frontend Types (camelCase)
// ========================================

/**
 * Answer generated by AI (frontend format)
 */
export interface AIGeneratedAnswer {
	content: string
	isCorrect: boolean
	explanation?: string
	point?: number
}

/**
 * Question generated by AI (frontend format)
 */
export interface AIGeneratedQuestion {
	content: string
	questionType: QuestionType
	cognitiveLevel: CognitiveLevel
	point: number
	mediaUrl?: string
	answers: AIGeneratedAnswer[]
	topicId?: string
}

/**
 * Topic configuration for AI generation matrix
 */
export interface AIMatrixTopicConfig {
	topicId: string
	topicName: string
	cognitiveLevel: CognitiveLevel
	quantity: number
}

/**
 * Response from batch question generation
 */
export interface GenerateQuestionsResponse {
	questions: AIGeneratedQuestion[]
	totalCount: number
}

/**
 * State for AI question generation in UI
 */
export interface AIGenerationState {
	isGenerating: boolean
	generatedQuestions: AIGeneratedQuestion[]
	error?: string
	progress?: {
		current: number
		total: number
	}
}

/**
 * Configuration options for AI generation
 */
export interface AIGenerationConfig {
	questionType: QuestionType
	cognitiveLevel: CognitiveLevel
	quantity: number
	topicId: string
	topicName: string
}
