import type { CognitiveLevel, QuestionType } from './exam-service/enums'

/**
 * Answer generated by AI
 */
export interface AIGeneratedAnswer {
	content: string
	isCorrect: boolean
	explanation?: string
	point?: number
}

/**
 * Question generated by AI
 */
export interface AIGeneratedQuestion {
	content: string
	questionType: QuestionType
	cognitiveLevel: CognitiveLevel
	point: number
	mediaUrl?: string
	answers: AIGeneratedAnswer[]
	topicId?: string
}

/**
 * Topic configuration for AI generation matrix
 */
export interface AIMatrixTopicConfig {
	topicId: string
	topicName: string
	cognitiveLevel: CognitiveLevel
	quantity: number
}

/**
 * Request to generate multiple questions based on a matrix
 */
export interface GenerateQuestionsRequest {
	subject: string
	grade: number
	matrixTopics: AIMatrixTopicConfig[]
	language?: 'vi' | 'en'
}

/**
 * Response from batch question generation
 */
export interface GenerateQuestionsResponse {
	questions: AIGeneratedQuestion[]
	totalCount: number
}

/**
 * Request to generate a single question
 */
export interface GenerateSingleQuestionRequest {
	subject: string
	grade: number
	topicName: string
	cognitiveLevel: CognitiveLevel
	questionType: QuestionType
	language?: 'vi' | 'en'
	topicDescription?: string
}

/**
 * State for AI question generation in UI
 */
export interface AIGenerationState {
	isGenerating: boolean
	generatedQuestions: AIGeneratedQuestion[]
	error?: string
	progress?: {
		current: number
		total: number
	}
}

/**
 * Configuration options for AI generation
 */
export interface AIGenerationConfig {
	questionType: QuestionType
	cognitiveLevel: CognitiveLevel
	quantity: number
	topicId: string
	topicName: string
}
